server:
  port: 8081
spring:
<<<<<<< HEAD
  datasource:
    url: jdbc:h2:mem:ms_catalogo
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
=======
  application:
    name: ms-catalogo-service

  datasource:
    url: jdbc:mysql://localhost:3306/ms_catalogo
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

>>>>>>> ba25d55be993052f0e325501025914843f307e62
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
<<<<<<< HEAD
      client:
        serviceUrl:
          defaultZone: http://localhost:8090/eureka
      instance:
        hostname: localhost
=======
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost






>>>>>>> ba25d55be993052f0e325501025914843f307e62
