server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
      #defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    hostname: localhost
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-ventas-service
          uri: lb://ms-ventas-service
          predicates:
            - Path=/ventas/**
        - id: ms-pagos-service
          uri: lb://ms-pagos-service
          predicates:
            - Path=/pagos/**
        - id: ms-clientes-service
          uri: lb://ms-clientes-service
          predicates:
            - Path=/clientes/**
        - id: ms-pedidos-service
          uri: lb://ms-pedidos-service
          predicates:
            - Path=/pedidos/**

